# PythonとNumpy基礎

---
## 目的
Pythonの基本的な使い方について確認する．



### Pythonプログラム
Pythonは近年，画像認識や機械学習等の人工知能研究分野で広く用いられているプログラミング言語です．<br>
Pythonの特徴は，<br>
1. 基本的な文法を簡潔に記述可能な言語
2. OSに依存しないユニバーサルな言語
3. 深層学習や画像認識，機械学習，データ解析に役立つモジュールが豊富に開発されている

### モジュール
モジュールとはPythonにおいて特定の計算を便利に行う，簡単に記述するためのプログラム群であり，C言語のライブラリに相当するものです．<br>
代表的なツールには，
* 行列演算など：numpy
* 科学技術計算など：scipy
* グラフの描画など：matplotlib
* 機械学習：scikit-learn
* ディープラーニング：pytorch, caffe, chainer
* 画像処理：pillow, scikit-image, opencv
* シミュレーション：simpy
* 解析的な計算：theano
* インタラクティブシェル：ipython

などが挙げられる．

---
### Pythonの型

Pythonの代表的な変数の型は下記が存在する：

* 数値型：整数，浮動小数点数，複素数
  - C言語のようなint, floatなどの型宣言は必要ありません
* コンテナ：リスト，タプル，辞書，集合
  - 型の混在が可能で，基本的にどんな型のデータでも代入可能
* 文字列
  - シングルクォート (') or ダブルクォート (") で囲むことで文字列として表現
* 定数：真偽値(True, False)，None(C言語のNULLに相当)

**【例】**　変数の定義<br>

In [1]:
# 整数，浮動小数点数
i = 100
f = 0.001

# コンテナ（リスト，タプル，辞書，集合）
l = [1, 0.01, "abcd"]
t = (3, -4.5, "defg")
d = {"a": 1.0, "b": 2.0, "c": 3.0}
s = {1, 2, 3}

# 真偽値
b1 = True
b2 = False

# None
n = None

**【例】**　コンテナへのアクセス<br>
コンテナの要素を取り出すには，角かっこ「[]」を利用する．
また，要素は0スタートである, i.e., [0,1,2,3...]

In [2]:
# 正数はタプル先頭からのインデックスを表す
print(t[2])
# 負数はタプル末尾からのインデックスを表す
print(t[-2])
# 末尾要素のみで構成されるタプル
print(t[-1:])
# 全要素を逆順に並べたタプル
print(t[::-1])

defg
-4.5
('defg',)
('defg', -4.5, 3)


**【例】**　文字列の整形<br>
C言語のprintf系関数のようなものです．
「%」演算子を利用します．
複数の変数を文字列に代入する場合は「()」を用いる．

In [3]:
# + 演算子で連結することが可能です
string1 = "abc" + "def"
print(string1)

# 文字列の整形方法
# 1. 一つの変数の場合
value = 10.111
string2 = "integer: %d" % value
print(string2)

# 2. 複数の場合
value1 = 10
float_val1 = 0.01
str1 = "abc"
string3 = "integer: %d, float value: %f, string: %s" % (value1, float_val1, str1)
print(string3)

abcdef
integer: 10
integer: 10, float value: 0.010000, string: abc


**【例】**　制御構文<br>
PythonでもC言語と同様の制御構文が用意されています．

* if文
* while文
* for文

PythonがC言語の記述と大きな異なる特徴として，これらの制御構文の対象範囲をインデントで表現することが挙げられます．
また，スペースの数はプログラム内で統一する必要があります．

In [4]:
# if文
a = -1
if a < 0:
    print("negative value")
elif a > 0:
    print("positive value")
else:
    print("zero")

# while文
print("==========")
b = 0
while b < 5:
    print(b)
    b += 1

# for文 1 
print("==========")
c = [0.1, 2.34, 5.6, 7.89]
for x in c:
    print(x)

negative value
0
1
2
3
4
0.1
2.34
5.6
7.89


**【例】**　関数定義<br>
Pythonの関数は「def」で定義を行います． 関数の定義でも上の制御構文と同様にインデントを用いて範囲を指定します．

In [5]:
# 関数定義
def addition_func(x, y):
    z = x + y
    return z
  
# 関数の実行
a = 10
b = 20
c = addition_func(a, b)
print(c)

30


また，C言語と異なり，複数の値を同時にreturnできる．（多重代入）

In [6]:
def sample_func(x, y):
    x = a + 1
    y = b * 2
    return x, y
  
c, d = sample_func(1, 2)
print(c, d)

11 40


---
### モジュールのインポート
先に説明したモジュールは「import」を用いることでプログラム内で使用することが可能です． <br>
ここでは，行列計算のモジュールである「Numpy」の使い方と合わせて説明します．

In [7]:
# 通常の読み込み
import numpy

# numpyという関数をnpという名前で使用できるように読み込む
import numpy as np

# numpy.linalgの中のnormという関数を読み込む（他は読み込まない）
from numpy.linalg import norm

### Numpyの使い方

**【例】**　N次元配列：ndarray <br>
Numpyでは上のリストやタプルとは異なり，型を統一する必要があります．

In [8]:
a = np.array([[0, 0, 1], [0, 0, 2]], dtype=np.float32) # dtype=***で配列要素の型を決めています
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
print(a)
print(b)

# 行列の演算（和・積）
c = a + b
d = a * b  # * は要素ごとの掛け算です
print(c)
print(d)

# （数学的な）行列の掛け算
e = np.dot(a, b.T)   # b.Tは行列bの転置を表しています
print(e)

[[0. 0. 1.]
 [0. 0. 2.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 4.]
 [4. 5. 8.]]
[[ 0.  0.  3.]
 [ 0.  0. 12.]]
[[ 3.  6.]
 [ 6. 12.]]


**【例】**　行列の扱い方<br>

* 特定の要素を取り出す（インデキシング）

`a[i, j]`：行列aの`(i, j)`要素を取り出します．

* 特定の範囲を切り出す（スライシング）
範囲を指定する際にはコロン「:」を用います

`a[i,:]`：行列aの`i`行目（のベクトル）

`a[:,j]`：行列aの`j`列目（のベクトル）

`a[:,0:3]`：行列aの`0, 1, 2`列目の部分行列

* ファンシーインデキシング

条件に合致する特定の要素のみを取り出します．
認識を失敗したデータだけを取り出す場合などに用いることができる便利な機能です．

In [9]:
# インデキシング
a_elem = a[0, 2]
print(a_elem)

# スライシング
a_slice1 = a[1, :]
a_slice2 = a[:, 2]
print(a_slice1)
print(a_slice2)

b_slice = b[1, 0:2]
print(b_slice)

# ファンシーインデキシング
a = np.array([1, 0, 1, 0, 0], dtype=np.int32)
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype=np.float32)
print(b[:, a == 1])

1.0
[0. 0. 2.]
[1. 2.]
[4. 5.]
[[0. 2.]
 [5. 7.]]


**【参考】** Numpyの便利な関数
Numpyには行列を演算するための便利な関数が多数含まれています．
以下では，いくつかの関数を紹介します．
ここで全てを紹介することは難しいので，興味のある方は公式のreferenceページへアクセスして調べてみてください．

[Numpy Reference (関数一覧の公式ページ)](https://docs.scipy.org/doc/numpy/reference/)

In [10]:
a = np.array([0,1,2], dtype=np.float32)

# exp(指数関数を要素ごとに計算)
print(np.exp(a))
# power(累乗)
print(np.power(a, 2))


# 集計用の関数(非ゼロの要素数を計算)
b = np.array([1, 0, 1, 0, 0], dtype=np.int32)
print(np.count_nonzero(b))

[1.        2.718282  7.3890557]
[0. 1. 4.]
2


---