# 層（Layer）
---
## 目的
深層学習におけるネットワークを構成するlayerについて理解し，代表的なlayerの機能を確認する．

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

### 深層学習と層
深層学習における代表的なモデルは，**多層パーセプトロン（Multi Layer erceptron: MLP）**です．<br>
MLPでは，形式ニューロン（formal neuron）と呼ばれる神経細胞の働きを模倣したモデルを最小構成としています．

<left>
<img src=https://onedrive.live.com/embed?resid=B8367B1E7E59C516%21562414&authkey=%21AEU0KwjGqODcy_Y&width=600&height=591
width=60%>
<br>
</left>

MLPでは，この形式ニューロンを1ユニットとして，層状に重ねることで神経細胞群の働きを模しています．<br>
深層学習（deep learning）とは，この隠れ層（中間層）を複数積み重ねることで，多層のMLPモデルを用いた機械学習のことを意味しています．，また，MLPでは，層の数やユニット数，各型式ユニットの接続等の調整が可能です．<br>
ここでは，代表的な層（layer）を紹介する．

---
### Fully Connected Layer (全結合層)<br>
一般的な全結合層を表すlayerであり，前の層のすべてのユニットが次の層のすべてのユニットと結合されている層です．
具体的には，入力$x\in\mathbb{R}^D$を与えたとき，次のように定義されます：
$$y = \sigma(Wx+b) \in \mathbb{R}^{D'}$$
ここで，$W\in\mathbb{R}^{D' \times D}$は重み行列，$b\in\mathbb{R}^{D'}$はバイアスを表しています．<br>
重み行列とバイアスは学習によって値が決まります．<br>
また，$\sigma(x):\mathbb{R}^{D'}\to\mathbb{R}^{D'}$は**活性化関数**と呼ばれるもので，任意に指定設定します．<br>
（実際には最後の出力層の活性化関数については問題の特性から決まることも多いです）<br>
一般に活性化関数には非線形関数を指定することで，MLPの性能を向上させます．

【Pytorchでの使い方】<br>
Fully Connected Layerを定義します.<br>
nn.Linearを使用して，入力サイズと出力サイズを指定します．<br>
今回は入力サイズ10,出力サイズ5で定義します．

In [5]:
# 例: 入力サイズが10、出力サイズが5のFully Connected Layerを定義
fc_layer = nn.Linear(10, 5)
print(fc_layer)

Linear(in_features=10, out_features=5, bias=True)


次に，入力データをこの層に渡してみましょう：

In [7]:
# 入力データの例
input_data = torch.randn(1, 10)
print('入力データ:',input_data)

# fc_layerに入力データを渡す
output_data = fc_layer(input_data)
print('出力データ:',output_data)

入力データ: tensor([[ 1.2560, -0.1070,  1.6364,  1.4183, -1.3964,  1.0110,  1.0284,  0.2446,
          0.7912,  0.4172]])
出力データ: tensor([[ 0.5544, -0.1074,  0.0605, -0.3395, -0.2279]],
       grad_fn=<AddmmBackward0>)


output_dataにはFully Connected Layerを通した結果が格納されます．<br>
この出力データは，入力データに対する重み行列の行列積にバイアスが加算された結果です．

Fully Connected Layerの重要なポイントは，モデルのパラメータの一部として重み行列とバイアスが自動的に学習されるということです．このため，これらのパラメータが訓練データに合わせて調整され，モデルがタスクに適応できるようになります．

---
### Activation（活性化関数）
PyTorchにおける活性化関数は，ニューラルネットワークの中間層で非線形性を導入するために使用されます．
以下では，代表的な活性化関数の使い方を説明します．<br>
（各関数の具体的な説明は$\S$Activationを参照してください．）

1. シグモイド関数（torch.nn.Sigmoid()）

In [8]:
# シグモイド関数を含む層の定義
sigmoid_layer = nn.Sigmoid()

# シグモイド関数を適用
output_data = sigmoid_layer(input_data)
print(output_data)

tensor([[0.7783, 0.4733, 0.8370, 0.8051, 0.1984, 0.7332, 0.7366, 0.5608, 0.6881,
         0.6028]])


2. ハイパボリックタンジェント関数（torch.nn.Tanh()）

In [9]:
# ハイパボリックタンジェント関数を含む層の定義
tanh_layer = nn.Tanh()

# ハイパボリックタンジェント関数を適用
output_data = tanh_layer(input_data)
print(output_data)

tensor([[ 0.8500, -0.1066,  0.9270,  0.8892, -0.8846,  0.7662,  0.7733,  0.2398,
          0.6591,  0.3946]])


3. ReLU関数（（torch.nn.ReLU()））

In [10]:
# ReLU関数を含む層の定義
relu_layer = nn.ReLU()

# ReLU関数を適用
output_data = relu_layer(input_data)
print(output_data)

tensor([[1.2560, 0.0000, 1.6364, 1.4183, 0.0000, 1.0110, 1.0284, 0.2446, 0.7912,
         0.4172]])


---
### Flatten（平滑化層）
Flattenは，多次元のテンソルを1次元のベクトルに変換する操作です．<br>
これは，畳み込みニューラルネットワーク（CNN）や深層学習モデルの全結合層に入力する前に，データを1次元に平坦化するために使用されます．<br>
具体的には，2次元の行列や3次元のテンソルを1列のベクトルに変換します．

【Pytorchでの使い方】<br>
PytorchにおけるFlatten(X)はｍ行列やテンソル$X \in \mathbb{R}^{m \times n}$を$$Flatten(X)=[X_{1,1},X_{1,2},\cdots,X_{1,n},X_{2,1},\cdots,X_{m,n}]$$と変形します．

In [15]:
# Flattenモジュールの定義
flatten_layer = nn.Flatten()

# 例: 3次元テンソルを作成
input_data = torch.randn(1, 3, 4, 4)  # (バッチサイズ, チャンネル数, 高さ, 幅)
print(input_data.size())
# Flatten操作を適用
output_data = flatten_layer(input_data)

# 結果の表示
print(output_data.size())

torch.Size([1, 3, 4, 4])
torch.Size([1, 48])


---
### Reshape（形状変換）
Reshapeは，テンソルの要素数を変えずに形状を変更する操作です．<br>
例えば，$2\times3$の行列を$1\times6$の行列に変換したり，3次元テンソルを1次元ベクトルに変換したりすることができます．
この操作は，データを異なるネットワーク層に適用する前に，データの形状を整えるために使用されます．

【Pytorchでの使い方】<br>

In [18]:
# 例: 3次元テンソルを1次元ベクトルに変換
tensor = torch.randn(2, 3, 4)  # (バッチサイズ, 行, 列)
print(tensor.size())

reshaped_tensor = tensor.view(-1)
print(reshaped_tensor.size())

# 例: 2x3の行列を1x6の行列に変換
matrix = torch.randn(2, 3)
print(matrix.size())
reshaped_matrix = matrix.view(1, -1)
print(reshaped_matrix.size())

torch.Size([2, 3, 4])
torch.Size([24])
torch.Size([2, 3])
torch.Size([1, 6])


---
### Permute（軸順序変更）
Permuteは，テンソルの次元の順序を変更する操作です．<br>
例えば，3次元テンソルが (batch_size, height, width) の順序である場合，これを (batch_size, width, height) の順序に変更できます．
これは，データの表現を変更せずに，異なる軸の順序でデータを見ることができる便利な操作です．

【Pytorchでの使い方】<br>
この例では，tensor.permute(0, 2, 1)は，元の順序 (0, 1, 2) を (0, 2, 1) に変更しています．したがって，元の高さが新しい幅に，元の幅が新しい高さになります．

In [19]:
# 例: 3次元テンソルの順序を変更
tensor = torch.randn(2, 3, 4)  # (バッチサイズ, 高さ, 幅)
print(tensor.size())
permuted_tensor = tensor.permute(0, 2, 1)  # (バッチサイズ, 幅, 高さ)
print(permuted_tensor.size())

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])


---
### RepeatVector
RepeatVectorは，与えられたベクトル（1次元テンソル）を指定された回数だけ繰り返し複製して，2次元以上のテンソルに変換する操作です．<br>
これにより，同じベクトルが指定された回数だけ繰り返された行列が得られます．例えば，ベクトル [1, 2, 3] を2回繰り返すと，行列 [[1, 2, 3], [1, 2, 3]] が得られます．

【Pytorchでの使い方】<br>
この例では，input_vector.repeat(3, 1)は，入力ベクトル [1, 2, 3] を3回繰り返して行列 [[1, 2, 3], [1, 2, 3], [1, 2, 3]] を生成しています．

In [23]:
# 例: ベクトルを3回繰り返し複製する
input_vector = torch.tensor([1, 2, 3])
print(input_vector)
repeated_matrix = input_vector.repeat(1, 3)  # (繰り返し回数, 1)
print(repeated_matrix)
repeated_matrix = input_vector.repeat(3, 1)  # (繰り返し回数, 1)
print(repeated_matrix)

tensor([1, 2, 3])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
